### ISSUE TITLE
Tool to compare keys of a YAML file

### ISSUE THREAD

**Issue by infertux** [infertux/dev_ideas#3]
The idea is to get a sort of `diff` between two YAML files based on the keys only.

One usecase would be to check completeness between translation files - https://github.com/buckybox/webstore/blob/master/bin/check_i18n is slow and ugly.

The tool could be implemented either as an interpreted script or a compiled and optimised binary.

**Comment by acatton** [comment]
https://github.com/acatton/yamlkeysdiff

The code is optimized, you can compile it with `-O2`. I haven't benchmarked it yet, it should be pretty fast. In theory, it should use `O(n+m)` space complexity, and `O(n*log(n)+m*log(m))` time complexity. (for diff between a file of size _n_ and another file of size _m_).

On my machine the binary weights 11M because it bundles the Haskell Yaml library.

**Comment by acatton** [comment]
Yeah my first benchmarks shows that it is very gluttonous in memory. I'm working on it. In the meantime it should be usable.

**Comment by infertux** [comment]
Wow! I wasn't expecting a solution so quickly @acatton! Actually, my plan was to build it in Rust... some day... but maybe I don't need to now. Thanks for building that :smiley:. I'm gonna give it a try...

**Comment by acatton** [comment]
@infertux there are some things I need to fix, for example:

``` yaml
a:
    aa: aa
    ab: ab
```

and:

``` yaml
b: b
```

gives this diff:

``` diff
> a:aa
> a:ab
< b
```

It should be:

``` diff
> a
< b
```

And there are other things on the TODO list: https://github.com/acatton/yamlkeysdiff#todo

**Comment by infertux** [comment]
Done! Alternative implementation as well: https://github.com/infertux/yamldiff
